### ISSUE TITLE
Arch Linux can't find Zenity

### ISSUE THREAD

**Issue by timebuzzerfelix** [redromnon/iBackep#7]
**Describe the bug**
Zenity in Linux Arch not found although installed

**To Reproduce**
1. Open the app by clicking on the app icon
2. Click on the "open folder" - Icon
3. Error message: "Looks like Zenity is not installed"

**System (please complete the following information):**
 - OS: Linux Arch
 - Zenity version 4.0.1 installed

**Comment by redromnon** [comment]
Please refer to #6 
Will mark this as duplicate.
